### ISSUE TITLE
Incorrect warranty dates for Dell machines

### ISSUE THREAD

**Issue by teejayen** [KelvinTegelaar/AzWarrantyUpdate#2]
Firstly, I must say a huge thank you for making this so easy to deploy, I've been manually running the PowerShell script up until now.

Noticed that when I first deployed this script, it made quite a number of changes to warranties that were already correct. A couple of example service tags, and the date the script has updated them to and then the correct date from the Dell website (manually looking up):

Dell Precision 5720 AIO   877X9P2   April 4, 2018   April 5, 2021
Dell XPS 13 9365   DS9CST2   Jan 20, 2019   Jan 22, 2021

The date it was updated to is the ship date, so my presumption is that it's grabbing the wrong field in the response from the Dell API.

Tried looking through the source code, but I couldn't find the configuration of `Update-WarrantyInfo` - not knowing / having looked too much into Azure Functions I presume this run from a separate repo / function that I as a user cannot see / interrogate.

**Comment by KelvinTegelaar** [comment]
Fixed. Seems like it was indeed pulling an older version of the PowerShell module. If you redeploy, or restart the app it should automatically pull the latest. :)

**Comment by teejayen** [comment]
It seems to now be updating with the expiration of the base warranty, but not if it was extended... see below:

![image](https://user-images.githubusercontent.com/12872656/112778482-0217d380-9088-11eb-9c79-272c7cf9f6d7.png)
![image](https://user-images.githubusercontent.com/12872656/112778593-37242600-9088-11eb-82ef-2775b011aa06.png)

For clarity, I would expect that the expiration date would be updated to Oct 11, 2021.
