### ISSUE TITLE
Extended warranty not being recognised

### ISSUE THREAD

**Issue by teejayen** [KelvinTegelaar/AzWarrantyUpdate#3]
It seems to now be updating with the expiration of the base warranty, but not if it was extended... see below:

![image](https://user-images.githubusercontent.com/12872656/112778482-0217d380-9088-11eb-9c79-272c7cf9f6d7.png)
![image](https://user-images.githubusercontent.com/12872656/112778593-37242600-9088-11eb-82ef-2775b011aa06.png)

For clarity, I would expect that the expiration date would be updated to Oct 11, 2021.

_Originally posted by @teejayen in https://github.com/KelvinTegelaar/AzWarrantyUpdate/issues/2#issuecomment-809018961_

**Comment by teejayen** [comment]
Wasn't sure of the Issue ettiquite, but I know I dislike run-on tickets so I have split this out into a seperate issue even though it somewhat relates to #2

**Comment by teejayen** [comment]
Further to the above, if I manually run PSWarranty on my local machine it does indeed get the correct End Date:

![image](https://user-images.githubusercontent.com/12872656/112934095-5db78f00-9164-11eb-95a6-c572e452c50a.png)

**Comment by KelvinTegelaar** [comment]
I'm expecting this is a difference between ordering in Windows PowerShell and PowerShell, on track to be fixed today.

**Comment by KelvinTegelaar** [comment]
And fixed it seems, please try again and let me know. The fastest way is to redeploy, or wait a day for the depency download to restart.

**Comment by teejayen** [comment]
Is there a way to get it to do a full run again? I removed the `lastrun.txt` file, thinking it might do it, but it seems not to have. I might remove the function entirely and set it up from scratch.

**Comment by teejayen** [comment]
I completely deleted all resources associated with the previous deployment, and have deployed again and it doesn't seem to be running.. is there a log file I can provide for you to review?

**Comment by teejayen** [comment]
Further to the above, I also ran the PSWarranty `update-warrantyinfo` command manually on my machine and it didn't update this machine with the correct warranty date.

**Comment by KelvinTegelaar** [comment]
Let me know which platform you're using, I'm thinking this has to do with the syncwithsource not processing right. :)

**Comment by teejayen** [comment]
ITGlue

**Comment by teejayen** [comment]
I ran PSWarranty manually with the `-OverwriteWarranty` and `-SyncWithSource` parameters and the warranties have been updated correctly. Reviewing `run.ps1`, this is exactly what happens with the automated process too.. so something strange going on.

**Comment by teejayen** [comment]
Have managed to get this working somehow or other. Didn't realise I could manually run the function through **Code + Test**. It kept on timing out (Consumption Model) so I have also increased the function to run for 10 minutes - refer to https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout
